### ISSUE TITLE
[Android] Unable to run the app

### ISSUE THREAD

**Issue by sattasundar** [naweed/MauiTubePlayer#1]
Tried to build and run on Android emulator, but getting this error;

<img src="https://user-images.githubusercontent.com/62828724/187478069-ecf949a9-6fef-497a-9d6e-a9923c1d5e8d.png"  width="200" height="400" />

Any configurations missing?

**Comment by naweed** [comment]
It might be due to the API key. I put in my API Key and everyone must have downloaded and used the same key to run the app. Google restricts number of API calls for free API calls. Plz replace the key in Models/Constants.cs file with your own API Key. I showed in Part 1 or 2 how to get the API Key for free from Google.

**Comment by naweed** [comment]
Yes, I checked and looks like my API key has been blocked. In fact all API keys under my account have been blocked.
